apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer
spec:
  selector:
    matchLabels:
      app: viewer
  replicas: 1
  template:
    metadata:
      labels:
        app: viewer
    spec:
      containers:
        - name: viewer
          image: jeesmon/ohif-viewer:v2.9.0.7055
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: APP_CONFIG
              value: /etc/viewer/app-config.js
            - name: NGINX_CONFIG
              value: /etc/viewer/nginx.conf
          volumeMounts:
            - name: viewer-config
              mountPath: /etc/viewer
      volumes:
        - name: viewer-config
          configMap:
            name: viewer-config
            items:
              - key: app-config.js
                path: app-config.js
              - key: nginx.conf
                path: nginx.conf
