name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Image
      run: docker build -t jeesmon/ohif-viewer:v4.9.8.14493 .
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Images
      if: ${{ github.ref == 'refs/heads/main' }}
      run: docker push jeesmon/ohif-viewer:v4.9.8.14493
